name: Docker Image Build

on:
  push:
    branches:
      - release-docker/**
    tags:
      - aiven-*
  pull_request:

jobs:
  build_docker:
    name: Build Docker image
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get version from the Git tag
        id: get_version
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/.* ]]
          then
            # If building a tag, use the same tag for the image
            echo ::set-output name=tag_version::${GITHUB_REF/refs\/tags\//}
          else
            echo ::set-output name=tag_version::${{ github.event.pull_request.head.sha || github.sha }}
          fi

      - name: Log in to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push if tagged
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/aiven/relay:${{ steps.get_version.outputs.tag_version }}
